words = [
    "CMAKE",
    "CXX",
    "DCMAKE",
    "EOF",
    "Werror",
    "bugprone",
    "conanfile",
    "cppcoreguidelines",
    "ctest",
    "direnv",
    "hicpp",
    "nixbuild",
    "nixos",
    "nixpkgs",
    "nullopt",
    "pkgs",
]
ignore_paths = ["flake.lock"]
